#BrowserName=chrome
BrowserName=Edge
#BrowserName=Safari
#BrowserName=IE
#BrowserName=FF
#BrowserName=Edge

#ApplicationURL=https://mail.rediff.com/cgi-bin/login.cgi
ApplicationURL=https://www.automationexercise.com/

username=user1
password=pass1