#Object Repository

#Element locator

#login page

login_username_id=login1
login_password_name=passwd
login_loginbttn_css=[class='signin-btn']


#Registration Page

login_register_email_rediff_xpath=//a[text()='Get a new Rediffmail ID']
register_fullName_css=[placeholder='Enter your full name']
register_emailid_css=[placeholder='Enter Rediffmail ID']

register_dob_day_css=[class='day']
register_gender_female_xpath=//label[text()='Female']


#Home Page

#https://www.automationexercise.com/
home_menu_products_xpath=//a[text()=' Products']
product_search_text_id=search_product
product_search_button_id=submit_search


